### ISSUE TITLE
app crashing on A15

### ISSUE THREAD

**Issue by sachinz25** [DanielSevillano/music-you#44]
**Whenever I click on any song to play app get crashed automatically.**

### Environment
App version: 0.7
Os version: Android 15

### Crashlog:
time: 1735411135655
msg: java.lang.IllegalArgumentException: cannot use a recycled source in createBitmap
stacktrace: java.lang.IllegalArgumentException: cannot use a recycled source in createBitmap
	at android.graphics.Bitmap.createBitmap(Bitmap.java:932)
	at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:854)
	at android.media.MediaMetadata$Builder.scaleBitmap(MediaMetadata.java:988)
	at android.media.MediaMetadata$Builder.build(MediaMetadata.java:970)
	at android.media.session.MediaSession.setMetadata(MediaSession.java:512)
	at it.vfsfitvnm.vimusic.service.PlayerService.onEvents(PlayerService.kt:576)
	at androidx.media3.exoplayer.ExoPlayerImpl.lambda$new$0(ExoPlayerImpl.java:299)
	at androidx.media3.exoplayer.ExoPlayerImpl.$r8$lambda$SA7gbpEMwf_Ft8S0LNQ1m_I4CcI(ExoPlayerImpl.java:0)
	at androidx.media3.exoplayer.ExoPlayerImpl$$ExternalSyntheticLambda19.invoke(R8$$SyntheticClass:0)
	at androidx.media3.common.util.ListenerSet$ListenerHolder.iterationFinished(ListenerSet.java:350)
	at androidx.media3.common.util.ListenerSet.handleMessage(ListenerSet.java:294)
	at androidx.media3.common.util.ListenerSet.$r8$lambda$rFcF5Pkb99AL585p5-2u78YfNkY(ListenerSet.java:0)
	at androidx.media3.common.util.ListenerSet$$ExternalSyntheticLambda0.handleMessage(R8$$SyntheticClass:0)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8706)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:585)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)

**Comment by DanielSevillano** [comment]
Do you experience the same issue with other forks of ViMusic?

**Comment by rushilvishwakarma** [comment]
Same Issue, A15.
```
time: 1736115869222
msg: java.lang.IllegalArgumentException: cannot use a recycled source in createBitmap
stacktrace: java.lang.IllegalArgumentException: cannot use a recycled source in createBitmap
	at android.graphics.Bitmap.createBitmap(Bitmap.java:932)
	at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:854)
	at android.media.MediaMetadata$Builder.scaleBitmap(MediaMetadata.java:996)
	at android.media.MediaMetadata$Builder.build(MediaMetadata.java:970)
	at android.media.session.MediaSession.setMetadata(MediaSession.java:512)
	at it.vfsfitvnm.vimusic.service.PlayerService.onEvents(PlayerService.kt:576)
	at androidx.media3.exoplayer.ExoPlayerImpl.lambda$new$0(ExoPlayerImpl.java:299)
	at androidx.media3.exoplayer.ExoPlayerImpl.$r8$lambda$SA7gbpEMwf_Ft8S0LNQ1m_I4CcI(ExoPlayerImpl.java:0)
	at androidx.media3.exoplayer.ExoPlayerImpl$$ExternalSyntheticLambda19.invoke(R8$$SyntheticClass:0)
	at androidx.media3.common.util.ListenerSet$ListenerHolder.iterationFinished(ListenerSet.java:350)
	at androidx.media3.common.util.ListenerSet.handleMessage(ListenerSet.java:294)
	at androidx.media3.common.util.ListenerSet.$r8$lambda$rFcF5Pkb99AL585p5-2u78YfNkY(ListenerSet.java:0)
	at androidx.media3.common.util.ListenerSet$$ExternalSyntheticLambda0.handleMessage(R8$$SyntheticClass:0)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8788)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:871)
```

**Comment by sachinz25** [comment]
> Do you experience the same issue with other forks of 

yes [vitune](https://github.com/25huizengek1/ViTune/issues/672) also facing the same error on a15 roms.

**Comment by DanielSevillano** [comment]
Is the app still crashing with the latest release?

**Comment by sachinz25** [comment]
this time crashlog is bit different than previous one but still crashing.

time: 1738429049707
msg: java.lang.IllegalStateException: Can't copy a recycled bitmap
stacktrace: java.lang.IllegalStateException: Can't copy a recycled bitmap
	at android.graphics.Bitmap.checkRecycled(Bitmap.java:419)
	at android.graphics.Bitmap.copy(Bitmap.java:715)
	at android.graphics.drawable.Icon.setBitmap(Icon.java:200)
	at android.graphics.drawable.Icon.createWithBitmap(Icon.java:826)
	at androidx.core.graphics.drawable.IconCompat$Api23Impl.toIcon(IconCompat.java:1269)
	at androidx.core.graphics.drawable.IconCompat.toIcon(IconCompat.java:529)
	at androidx.core.app.NotificationCompatBuilder.<init>(NotificationCompatBuilder.java:102)
	at androidx.core.app.NotificationCompat$Builder.build(NotificationCompat.java:2524)
	at it.vfsfitvnm.vimusic.service.PlayerService.notification(PlayerService.kt:706)
	at it.vfsfitvnm.vimusic.service.PlayerService.onEvents(PlayerService.kt:595)
	at androidx.media3.exoplayer.ExoPlayerImpl.lambda$new$0(ExoPlayerImpl.java:296)
	at androidx.media3.exoplayer.ExoPlayerImpl.$r8$lambda$SA7gbpEMwf_Ft8S0LNQ1m_I4CcI(ExoPlayerImpl.java:0)
	at androidx.media3.exoplayer.ExoPlayerImpl$$ExternalSyntheticLambda19.invoke(R8$$SyntheticClass:0)
	at androidx.media3.common.util.ListenerSet$ListenerHolder.iterationFinished(ListenerSet.java:353)
	at androidx.media3.common.util.ListenerSet.handleMessage(ListenerSet.java:297)
	at androidx.media3.common.util.ListenerSet.$r8$lambda$rFcF5Pkb99AL585p5-2u78YfNkY(ListenerSet.java:0)
	at androidx.media3.common.util.ListenerSet$$ExternalSyntheticLambda0.handleMessage(R8$$SyntheticClass:0)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8706)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:585)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
